###
# sets up the Supervisor configuration and handles any restarting issues
# that can sometimes occur with supervisor.sock
#
---

- name: check if supervisor.sock exists
  stat: path=/var/run/supervisor.sock
  register: supervisor_sock_file

- name: delete supervisor.sock file so supervisor can start
  command: rm /var/run/supervisor.sock
  sudo: yes
  when: supervisor_sock_file.stat.exists

- name: write supervisor uwsgi configuration for web application
  template: src=uwsgi_supervisor.conf.j2 dest=/etc/supervisor/conf.d/uwsgi_{{app_name}}.conf
  sudo: yes
  when: uwsgi_mode

- name: write supervisor gunicorn configuration for web application
  template: src=gunicorn_supervisor.conf.j2 dest=/etc/supervisor/conf.d/gunicorn_{{app_name}}.conf
  sudo: yes
  when: gunicorn_mode

- name: write supervisor celery configuration
  template: src=celery_supervisor.conf.j2 dest=/etc/supervisor/conf.d/celery_{{app_name}}.conf
  sudo: yes

- name: write default supervisor DAEMON_OPTS
  lineinfile: dest=/etc/default/supervisor regexp='DAEMON_OPTS' line='DAEMON_OPTS="-c /etc/supervisor/supervisord.conf"'
  sudo: yes

- name: link supervisord.conf to default location
  file: path=/etc/supervisord.conf
        src=/etc/supervisor/supervisord.conf
        state=link
        force=yes
  sudo: yes
  notify:
    - restart supervisor
    - restart nginx
