###
# updates the APT package cache and install packages necessary for web
# servers
#
---

- name: ensure apt cache is up to date
  apt: update_cache=yes
  sudo: yes

- name: ensure web server packages are installed
  apt: name={{item}}
  sudo: yes
  with_items:
    - tig
    - git
    - libpq-dev
    - nginx
    - supervisor
    - libpq-dev
    - python-dev
    - python-setuptools
    - python-pip
    - python-virtualenv
    - python-mysqldb
    - ipython
    - libmysqlclient-dev
    - mysql-client
    - libxml2
    - libxml2-dev
    - libxslt1-dev
